### ISSUE TITLE
Importing Non Exisiting componets/files

### ISSUE THREAD

**Issue by morisha** [BuildForSDGCohort2/Team-159-Frontend#4]
In `App.js` you imported
`import logo from './logo.svg';`
`import './App.css';`
which are not existing thus the app failing to compile!

Ref: https://github.com/BuildForSDGCohort2/Team-159-Frontend/blob/ffa0f07937f759095eef055cba092f8644394978/src/App.js#L2-L3

**Comment by Marvellous1** [comment]
Fixed it, waiting for pr to be merged.

Thanks anyway
